# ansible-playbook -u pi -k -i 'TARGET-DHCP-IP,' password.yml
---

- name: Default "pi" account password and hostname reset playbook
  hosts: all
  become: yes
  roles:
     - customize

  vars_prompt:
    - name: "pi_password"
      prompt: "New pi account password"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
    - name: "pi_hostname"
      prompt: "New pi hostname"
