---
- name: install audio packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - pulseaudio
    - pavucontrol
    - pulseaudio-equalizer
  become: yes

- name: Create a directory if it does not exist
  file:
    path: ~/bin/
    state: directory
    mode: '0755'

- name: Template a startup for audio
  template:
    src: setup_pulseaudio.sh
    dest: ~/bin/setup_pulseaudio.sh
    mode: '0700'