---
- apt_repository:
    repo: "ppa:regolith-linux/release"
    state: present
  become: yes

- name: update the apt package index i.e. apt-get update
  apt: update_cache=yes
  become: yes

- name: upgrade system packages i.e. apt-get upgrade
  apt: upgrade=yes
  become: yes

- name: install regolith packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - regolith-desktop
    - i3xrocks-net-traffic
    - i3xrocks-cpu-usage
    - i3xrocks-time
  become: yes


- name: install admin packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - glances
  become: yes