---
- name: update the apt package index i.e. apt-get update
  apt: update_cache=yes
  become: yes

- name: upgrade system packages i.e. apt-get upgrade
  apt: upgrade=yes
  become: yes

- name: install i3 packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - i3 
    - dmenu 
    - suckless-tools
  become: yes

- name: set i3 as wm
  alternatives:
    name: x-window-manager
    path: /usr/bin/i3
  become: yes

- name: set i3 as wm
  ini_file: dest=/etc/lightdm/lightdm.conf section=Seat:* option=user-session value=i3 backup=yes
  become: yes

# include an i3 configuration
- name: temlpate an i3 configuration
  template:
    src: config.j2
    dest: ~/.config/i3/config

#Disable oversan (probably many will not want/need this. Variable?)
# https://dev.to/nabbisen/raspbian-enlarge-screen-boundaries-via-overscan-settings-2ef
- name: Disable oversan 
  become: yes
  lineinfile:
    path: /boot/config.txt
    regexp: '^[\#]*disable_overscan='
    line: disable_overscan=1

# Don't sleep the screen
- name: Disable screen sleep
  become: yes
  ini_file: dest=/etc/lightdm/lightdm.conf section=SetDefaults option=xserver-command value="X -s 0 dpms" backup=yes
  become: yes

- name: Reboot system if required
  command: shutdown -r now 'Rebooting to complete system upgrade'
            removes=/var/run/reboot-required